"use client";

import { motion } from "framer-motion";
import { LiveSignalFeed } from "./LiveSignalFeed";

const EASE = [0.16, 1, 0.3, 1] as const;

export function LiveDemo() {
  return (
    <section className="relative section-lavender-wash py-24 md:py-32 overflow-hidden">
      <div
        aria-hidden
        className="absolute inset-0 opacity-50 pointer-events-none"
        style={{
          backgroundImage: "url(/topo-bg-light.svg)",
          backgroundSize: "cover",
        }}
      />
      <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 0.6, ease: EASE }}
          className="text-center mb-10"
        >
          <h2
            className="font-bold tracking-tight text-[#0f172a]"
            style={{ fontSize: "clamp(1.75rem, 3.2vw, 2rem)" }}
          >
            See signals in real-time
          </h2>
          <p className="mt-3 text-[14px] text-[#334155] max-w-xl mx-auto">
            These are example signals generated by the platform — the same
            cards operators see in their daily workflow.
          </p>
        </motion.div>

        <div className="flex items-center justify-center gap-2 mb-5 font-mono text-[11px] text-[#64748b]">
          <span className="relative inline-flex w-2 h-2">
            <span className="absolute inset-0 rounded-full bg-[#14b8a6] animate-ping opacity-70" />
            <span className="relative rounded-full w-2 h-2 bg-[#14b8a6]" />
          </span>
          Signal feed — live
        </div>

        <LiveSignalFeed />
      </div>
    </section>
  );
}
